### ISSUE TITLE
Error During Authentication: in AccountService

### ISSUE THREAD

**Issue by zoltanhalasz** [cornflourblue/aspnet-core-3-signup-verification-api#16]
When trying to generate JWT (method generateJwtToken), during authentication, it throws the following error:
at line:
   var token = tokenHandler.CreateToken(tokenDescriptor);

error details:

System.ArgumentOutOfRangeException
  HResult=0x80131502
  Message=IDX10653: The encryption algorithm 'System.String' requires a key size of at least 'System.Int32' bits. Key 'Microsoft.IdentityModel.Tokens.SymmetricSecurityKey', is of size: 'System.Int32'. (Parameter 'key')
  Source=Microsoft.IdentityModel.Tokens
  StackTrace:
   at Microsoft.IdentityModel.Tokens.SymmetricSignatureProvider..ctor(SecurityKey key, String algorithm, Boolean willCreateSignatures)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateSignatureProvider(SecurityKey key, String algorithm, Boolean willCreateSignatures, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, String algorithm, Boolean cacheProvider)
   at Microsoft.IdentityModel.Tokens.CryptoProviderFactory.CreateForSigning(SecurityKey key, String algorithm)
   at Microsoft.IdentityModel.JsonWebTokens.JwtTokenUtilities.CreateEncodedSignature(String input, SigningCredentials signingCredentials)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateJwtSecurityTokenPrivate(String issuer, String audience, ClaimsIdentity subject, Nullable`1 notBefore, Nullable`1 expires, Nullable`1 issuedAt, SigningCredentials signingCredentials, EncryptingCredentials encryptingCredentials, IDictionary`2 claimCollection)
   at System.IdentityModel.Tokens.Jwt.JwtSecurityTokenHandler.CreateToken(SecurityTokenDescriptor tokenDescriptor)
   at WebApi.Services.AccountService.generateJwtToken(Account account) in C:\Dotnet\aspnet-core-3-signup-verification-api\Services\AccountService.cs:line 294
   at WebApi.Services.AccountService.Authenticate(AuthenticateRequest model, String ipAddress) in C:\Dotnet\aspnet-core-3-signup-verification-api\Services\AccountService.cs:line 62
   at WebApi.Controllers.AccountsController.Authenticate(AuthenticateRequest model) in C:\Dotnet\aspnet-core-3-signup-verification-api\Controllers\AccountsController.cs:line 30
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()

**Comment by AcidRaZor** [comment]
Your secret key is too small / not set
